### PR TITLE
Feature/ad panel

### PR DESCRIPTION
**Pull request by monodelic**
admin panel added

### CODE REVIEW

**Comment by artempartos** [comment]
solve conflicts - rebase against develop

**Comment by monodelic** [comment]
there are no conflicts against develop.
what should i do next? merge?

**Comment by artempartos** [comment]
nope

**Comment by artempartos** [comment]
rebase and stash commits

**Comment by monodelic** [comment]
All done.
So what's the next step in the plan?

**Comment by artempartos** [comment]
👍

**Pull request merged**
